config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :edit, :show, :update, :destroy], shallow: true do
  	member do
  		get 'like'
  		get 'history'
  		get 'follow'
      get 'novels'
      get 'novel_contents'
      patch 'user_restore'
  	end
  end
  resources :novels do
  	collection do
  		get 'ranking'
      get 'novels_admin_index'
    end
    member do
      patch 'novel_restore'
  	end
  	resources :novel_contents, only: [:show, :new, :edit, :update, :destroy, :create]  do
  		resources :comments, only: [:create, :destroy]
  		resource :likes, only: [:create, :destroy]
  		resource :history, only: [:create, :destroy]
        member do
          patch 'novel_content_restore'
  	     end
    end
  end
  root 'novels#index'
  get 'about/index'
  get 'novel_contents/index'
  resources :genres, only: [:new, :create, :destroy]
  get 'tags/:tag', to: 'novels#index', as: :tag
  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :novels, dependent: :destroy
  has_many :novel_contents, dependent: :destroy
  has_many :histories, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  validates :username, presence: true, uniqueness: true, length: { maximum: 15, minimum: 3 }
  validates :user_about, length: { maximum: 300 }

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_admin, only: [:index]
  before_action :authenticate_user!, only: [:edit, :history]
  before_action :correct_user, only: [:edit]
  before_action :user_history, only: [:history]
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @novels = Novel.where(user_id: @user.id).order(created_at: "desc")
    @novel_contents = NovelContent.where(user_id: @user.id).order(created_at: "DESC")
    @likes = Like.where(user_id: @user.id)
    @follows = User.find(Relationship.where(user_id: @user).order(created_at: "desc").pluck(:follow_id))
    @follower = User.find(Relationship.where(follow_id: @user).order(created_at: "desc").pluck(:user_id))
    @history = History.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "マイページを更新しました"
      redirect_to user_path(@user.id)
    else
      render action: "edit"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:alert] = "退会しました"
    redirect_to users_path
  end

  def like
    @user = User.find(params[:id])
    @likes = Like.page(params[:page]).where(user_id: @user.id).order(created_at: "DESC")
  end

  def follow
    @user = User.find(params[:id])
    @follows = User.page(params[:page]).find(Relationship.where(user_id: @user).order(created_at: "desc").pluck(:follow_id))
    @follower = User.page(params[:page]).find(Relationship.where(follow_id: @user).order(created_at: "desc").pluck(:user_id))
  end

  def history
    @user = User.find(params[:id])
    @history = History.where(user_id: @user.id)
  end

  def novels
    @user = User.find(params[:id])

    @novels = Novel.page(params[:page]).where(user_id: @user).order(created_at: "DESC")
  end

  def novel_contents
    @user = User.find(params[:id])
    @novel_contents = NovelContent.page(params[:page]).where(user_id: @user).order(created_at: "DESC")
  end

  def user_restore
    @user = User.only_deleted.find(params[:id]).restore
    flash[:notice] = "#{@user.username}を復元しました"
    redirect_to users_path
  end
end
private
def user_admin
  @users = User.page(params[:page]).with_deleted
  if current_user.admin == false
    redirect_to root_path
  else
    render :index
  end
end

def user_params
  params.require(:user).permit(:username, :email, :user_about)
end

def correct_user
  @user = User.find(params[:id])
  if current_user.admin || current_user == @user
    render :edit
  else
    flash[:alert] = "権限がありません"
    redirect_to user_path(@user)
  end
  # if current_user.admin
  #      render :edit
  # elsif current_user != @user
  #      redirect_to new_user_registration_path
  # else
  #   render :edit
  # end
end

def user_history
  @user = User.find(params[:id])
  @history = History.where(user_id: @user.id)
  if current_user.admin || current_user == @user
    render :history
  else
    flash[:alert] = "権限がありません"
    redirect_to user_path(@user)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_mypage_link.html.erb
<% if current_user == user %>
<%= link_to "マイページへ", user_path(current_user) , class: "btn btn-primary btn-block"%>
<% else %>
<%= link_to "#{user.username}さんのマイページへ", user_path(user) , class: "btn btn-primary btn-block"%>
<% end %>

app/views/users/edit.html.erb
<%= render "common/header" %>
<div class ="body" >
	<div class ="container">
		<div class ="row">
			<div class ="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3  col-xs-12">
				<% if @user.errors.any? %>
					<div id="error_explanation">
						<ul>
							<h3><%= @user.errors.count %>件のエラーです</h3>
							<% @user.errors.full_messages.each do |message| %>
							<li><%= message %></li>
							<% end %>
						</ul>
					</div>
				<% end %>
				<div class= "form-header">
					<h2>登録情報編集</h2>
				</div>
				<div class= "form-body">
					<%=  form_with model: @user, local: true do |f|  %>
					<%= render "devise/shared/error_messages", resource: resource %>
                    <div class="form-group">
                      <div class="field">
                        <%= f.label :username, "ユーザーネーム" %><br />
                        <%= f.text_field :username, autofocus: true, class:"form-control " , id:"username", placeholder:"3~15文字" %>
                      </div>
                    </div>
                     <div class="form-group">
                      <div class="field">
                        <%= f.label :email %><br />
                        <%= f.email_field :email, autofocus: true, class:"form-control " , id:"email", placeholder:"メールアドレス" %>
                      </div>
                    </div>
                     <div class="form-group">
                      <div class="field user_about_field">
                        <%= f.label :user_about, "自己紹介　~300文字" %><br />
                        <%= f.text_area :user_about, autofocus: true, class:"form-control " , id:"user_about", placeholder:"~300文字" %>
                        <p id="counter-7">0文字</p>
                      </div>
                    </div>
                    <div class="actions">
                        <%= f.submit "更新" , class: "btn btn-block btn-warning "  %>
                    </div>
                    <%= render partial: "users/mypage_link", locals: {user: @user} %>
					<% end %>
					<div class= "actions destroy">
                    	<%= button_to "退会",registration_path(resource_name),data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-block btn-danger" %>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
<%= render "common/footer" %>

app/views/users/follow.html.erb
<%= render "common/header" %>
<div class= "show_head" >
	<h3><%= @user.username %>さんのフォローユーザー</h3>
</div>
<div class= "body">
	<div class= "container">
		<div class= "row">
			<% if @follows.blank? %>
				<div class= "follow-box">
		 			<div class= "box_head">
	 					<h2>フォローしている人はいません</h2>
	 				</div>
 				</div>
 			<%  else %>
				<div class= "col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1" >
					<div class= "follow-box">
						<% @follows.each do |f| %>
						<h4><%= link_to f.username, user_path(f) %></h4>
						<div class= "show_novels_box">
							<div class= "box_head">
								<h4>投稿小説</h4>
							</div>
							<% if f.novel_contents.blank? %>
								<div class= "box_head">
									<h2>投稿小説はありません</h2>
								</div>
							<% else %>
								<% f.novel_contents.last(1).each do |n| %>
								<%= render partial: "novels/content" ,locals: {f: n} %>
								<% end %>
								<div class= "box_head">
								<%= link_to "投稿小説一覧", novel_contents_user_path(f), class: "btn btn-primary" %>
								</div>
							<% end %>
						</div>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>

	<div class= "show_head" >
		<h3><%= @user.username %>さんのフォロワー</h3>
	</div>
	<div class= "container">
		<div class= "row">
			<% if @follower.blank? %>
				<div class= "follow-box">
		 			<div class= "box_head">
		 				<h2>フォロワーはいません</h2>
		 			</div>
	 			</div>
 			<% else %>
				<div class= "col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1" >
					<div class= "follow-box">
					<% @follower.each do |f| %>
						<table class= "table" >
							<thead>
								<th>ID</th>
								<th>ユーザーネーム</th>
							</thead>
							<tbody>
							<tr>
								<td><%= f.id %></td>
								<td><%= link_to f.username, user_path(f) %></td>
							</tr>
						    </tbody>
						</table>
					<% end %>
					</div>
				</div>
			<% end %>
		</div>
		<%= render partial: "users/mypage_link", locals: {user: @user} %>
	</div>
</div>
<%= render "common/footer" %>

app/views/users/history.html.erb
<%= render "common/header" %>
<div class= "show_head" >
	<h3><%= @user.username %>さんの閲覧履歴</h3>
	<h4>最大20件</h4>
</div>
<div class= "body">
	<div class= "container">
		<div class= "row">
			<% if @history.blank? %>
	 		<div class= "box_head">
	 			<h2>閲覧履歴はありません</h2>
 			</div>
 			<%= render partial: "users/mypage_link", locals: {user: @user} %>
 		</div>
 		<%  else %>
		<div class= "row">
			<div class= "col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1" >
				<div class= "ranking-box">
				<% @history.each do |f| %>
					<%= render partial: "novels/novel_content", locals: {f: f} %>
				<% end %>
				</div>
				<%= render partial: "users/mypage_link", locals: {user: @user} %>
			</div>
		</div>
		<% end %>
	</div>
</div>
<%= render "common/footer" %>

app/views/users/index.html.erb
<%= render "common/header" %>
<div class=body>
	<%= render "common/alert" %>
	<div  class="container">
		<div class= "row">
			<div  class= "col-lg-10 col-offset-1 col-md-10 col-md-offset-1 col-xs-12">
				<%= render "common/alert" %>
				<table class= "table table-hover">
					<thead>
						<tr>
							<th class= "col-lg-1 col-md-1 col-xs-1">ID</th>
							<th class= "col-lg-5 col-md-5 col-xs-5">ユーザーネーム</th>
							<th class= "col-lg-3 col-md-3 col-xs-3">編集</th>
							<th class= "col-lg-3 col-md-3 col-xs-3">削除</th>
						</tr>
					</thead>
					<tbody>
						<% @users.each do |f| %>
						<tr>
							<% unless f.deleted_at? %>
							<td class= "col-lg-1 col-md-1 col-xs-1"><%= f.id %></td>
							<td class= "col-lg-5 col-md-5 col-xs-5"><%= link_to f.username, user_path(f.id) %></td>
							<td class= "col-lg-3 col-md-3 col-xs-3"><%= link_to "編集",  edit_user_path(f.id), class: "btn btn-primary" %></td>
							<td class= "col-lg-3 col-md-3 col-xs-3"><%= link_to "アカウント削除", f, data: { confirm: "退会させますか?" }, method: :delete , class: "btn btn-danger"%></td>
							<% else %>
							<td class= "col-lg-1 col-md-1 col-xs-1"><%= f.id %></td>
							<td class= "col-lg-5 col-md-5 col-xs-5"><%= f.username %></td>
							<td class= "col-lg-3 col-md-3 col-xs-3"><%= link_to "編集",  edit_user_path(f.id), class: "btn btn-primary disabled" %></td>
							<td class= "col-lg-3 col-md-3 col-xs-3"><%= link_to "アカウント復元",user_restore_user_path(f), method: :patch  , class: "btn btn-success"%></td>
							<% end %>
						</tr>
						<% end %>
					</tbody>
				</table>
				<%= paginate @users %>
			</div>
		</div>
	</div>
</div>
<%= render "common/footer"  %>

app/views/users/like.html.erb
<%= render "common/header" %>
<div class= "show_head" >
	<h3><%= @user.username %>さんのお気に入り一覧</h3>
</div>
<div class= "body">
	<div class= "container">
		<div class= "row">
			<% if @likes.blank? %>
	 		<div class= "box_head">
	 			<h2>お気に入り小説はありません</h2>
	 		</div>
 			<%= render partial: "users/mypage_link", locals: {user: @user} %>
 		</div>
 		<%  else %>
		<div class= "row">
			<div class= "col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1" >
				<div class= "ranking-box">
				<% @likes.each do |f| %>
					<%= render partial: "novels/novel_content", locals: {f: f} %>
				<% end %>
				</div>
				<%= paginate @likes %>
				<%= render partial: "users/mypage_link", locals: {user: @user} %>
			</div>
		</div>
		<% end %>
	</div>
</div>
<%= render "common/footer" %>

app/views/users/novel_contents.html.erb
<%= render "common/header" %>
<div class= "body">
	<div class= "show_head">
 			<h3><%= @user.username %>さんの投稿小説一覧</h3>
 		</div>
	<div class= "container-fluid">
 		<% if @novel_contents.blank? %>
 		<div class= "box_head">
 			<h2>投稿小説はありません</h2>
 		</div>
 		<%= render partial: "users/mypage_link", locals: {user: @user} %>
 		<%  else %>
		<div class= "row">
			<div class= "col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1" >
				<div class= "show_novels_box">
				<% @novel_contents.each do |f| %>
					<%= render partial: "novels/content" ,locals: {f: f} %>
				<% end %>
				</div>
				<%= paginate @novel_contents %>
				<%= render partial: "users/mypage_link", locals: {user: @user} %>
			</div>
		</div>
		<% end %>
	</div>
</div>
<%= render "common/footer" %>

app/views/users/novels.html.erb
<%= render "common/header" %>
<div class= "body">
	<%= render "common/alert" %>
	<div class= "show_head">
 			<h3><%= @user.username %>さんの投稿作品一覧</h3>
 		</div>
	<div class= "container-fluid">
 		<% if @novels.blank? %>
 		<div class= "box_head">
 			<h2>投稿作品はありません</h2>
 		</div>
 		<%= render partial: "users/mypage_link", locals: {user: @user} %>
 		<%  else %>
		<div class= "row">
			<div class= "col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1" >
				<div class= "show_novels_box">
				<% @novels.each do |f| %>
					<%= render partial: "novels/novel" ,locals: {f: f} %>
				<% end %>
				</div>
				<%= paginate @novels %>
				<%= render partial: "users/mypage_link", locals: {user: @user} %>
			</div>
		</div>
		<% end %>
	</div>
</div>
<%= render "common/footer" %>

app/views/users/show.html.erb
 <%= render "common/header" %>
 <div class= "body">
 	<%= render "common/alert" %>
 	<div class= "show_head" >
 		<h3><%= @user.username %>さんのマイページ</h3>
 		<% if user_signed_in? %>
	 		<% if current_user == @user || current_user.admin? %>
	 		<%= link_to "編集", edit_user_path(@user.id), class: "btn btn-info" %>
	 		<% end %>
	 		<div id= "follow_btn">
	 			<%= render partial: 'relationships/follow', locals: {user: @user} , lacal: true %>
	 		</div>
	 	<% end %>
 	</div>
 	<div class= "container-fluid">
 		<div class= "row">
	 		<div class= "col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-xs-10 col-xs-offset-1 order-lg-2 col-lg-push-3 col-md-push-3" >
	 			<div class= "show_novels_box">
	 				<div class= "box_head">
	 				<h4>投稿作品</h4>
	 				</div>
	 				<% if @novels.blank? %>
	 				<div class= "box_head">
	 					<h2>投稿作品はありません</h2>
	 				</div>
	 				<% else %>
		 				<% @novels.last(3).each do |f| %>
		 					<%= render partial: "novels/novel" ,locals: {f: f} %>
						<% end %>
					<div class= "box_head">
					<%= link_to "投稿作品一覧", novels_user_path(@user.id),  class: "btn btn-primary" %>
					</div>
					<%  end %>
				</div>
				<div class= "show_novels_box">
					<div class= "box_head">
						<h4>投稿小説</h4>
					</div>
					<% if @novel_contents.blank? %>
					<div class= "box_head">
						<h2>投稿小説はありません</h2>
					</div>
					<%  else %>
					<% @novel_contents.last(3).each do |f| %>
						<%= render partial: "novels/content" ,locals: {f: f} %>
					<% end %>
						<div class= "box_head">
						<%= link_to "投稿小説一覧", novel_contents_user_path(@user.id), class: "btn btn-primary" %>
						</div>
					<% end  %>
				</div>
			</div>
			<div class= "col-lg-3  col-md-3 col-xs-10  col-lg-offset-0 col-md-offset-0 col-xs-offset-1 col-lg-pull-6 col-md-pull-6 ">
				<div class=  "show_novels_box">
					<div class= "box_head">
						<h4>お気に入り小説</h4>
					</div>
					<% if @likes.blank? %>
			 			<div class= "box_head">
			 				<h2>お気に入り小説はありません</h2>
			 			</div>
	 				<% else %>
						<% @likes.last(5).each do |f| %>
							<%= render partial: "novels/novel_content", locals: {f: f} %>
						<% end %>
						<div class= "box_head">
							<%= link_to "お気に入り小説一覧", like_user_path(@user), class: "btn btn-primary" %>
						</div>
					<% end %>
				</div>
			</div>
			<div class= "col-lg-3  col-md-3 col-xs-10  col-lg-offset-0 col-md-offset-0 col-xs-offset-1 ">
				<% if user_signed_in? %>
			    <% if current_user = @user || current_user.admin?  %>
				<div class=  "show_novels_box">
					<div class= "box_head">
						<h4>閲覧履歴</h4>
					</div>
					<% if @history.blank? %>
			 			<div class= "box_head">
			 				<h2>閲覧履歴はありません</h2>
			 			</div>
	 				<% else %>
						<% @history.last(3).each do |f| %>
							<%= render partial: "novels/novel_content", locals: {f: f} %>
						<% end %>
						<div class= "box_head">
							<%= link_to "閲覧履歴へ", history_user_path(@user), class: "btn btn-primary" %>
						</div>
					<% end %>
				</div>
				<% end %>
				<% end %>
				<div class=  "show_novels_box">
					<% if @follows.blank? %>
			 			<div class= "box_head">
			 				<h6>フォローしているユーザーはいません</h6>
			 			</div>
	 				<% else %>
	 				<div class= "box_head">
						<h4>Follow</h4>
					</div>
		 				<table class= "table-follow">
							<thead>
								<th>ID</th>
								<th>ユーザーネーム</th>
								</thead>
							<% @follows.last(10).each do |f| %>
								<tbody>
									<td><%= f.id %></td>
									<td><%= link_to f.username, user_path(f) %></td>
								</tbody>
							<% end %>
						</table>
					<% end %>
					<% if @follows.present? %>
					<div class= "box_head">
						<%= link_to "Follow一覧", follow_user_path(@user), class: "btn btn-primary" %>
					</div>
					<% end %>
				</div>
				<div class=  "show_novels_box">
					<% if @follower.blank? %>
						<div class= "box_head">
				 			<h6>フォローされているユーザーはいません</h6>
				 		</div>
				 	<% else %>
				 	<div class= "box_head">
						<h4>Follower</h4>
					</div>
				 		<table class= "table-follow">
						<thead>
							<th>ID</th>
							<th>ユーザーネーム</th>
							</thead>
						<% @follower.last(10).each do |f| %>
							<tbody>
								<td><%= f.id %></td>
								<td><%= link_to f.username, user_path(f) %></td>
							</tbody>
						<% end %>
						</table>
					<% end %>
					<% if @follower.present? %>
					<div class= "box_head">
						<%= link_to "Follow一覧", follow_user_path(@user), class: "btn btn-primary" %>
					</div>
					<% end %>
				</div>
			</div>
			<div class= "col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1" >
				<div class= "user_about">
					<table >
						<tr>
							<th>ID</th>
							<td><%= @user.id %></td>
						</tr>
						<tr>
							<th>ユーザーネーム</th>
							<td><%= @user.username %></td>
						</tr>
						<tr>
							<th>自己紹介</th>
							<td><%= @user.user_about %></td>
						</tr>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<%= render "common/footer" %>