config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :edit, :show, :update, :destroy], shallow: true do
  	member do
  		get 'like'
  		get 'history'
  		get 'follow'
      get 'novels'
      get 'novel_contents'
      patch 'user_restore'
  	end
  end
  resources :novels do
  	collection do
  		get 'ranking'
      get 'novels_admin_index'
    end
    member do
      patch 'novel_restore'
  	end
  	resources :novel_contents, only: [:show, :new, :edit, :update, :destroy, :create]  do
  		resources :comments, only: [:create, :destroy]
  		resource :likes, only: [:create, :destroy]
  		resource :history, only: [:create, :destroy]
        member do
          patch 'novel_content_restore'
  	     end
    end
  end
  root 'novels#index'
  get 'about/index'
  get 'novel_contents/index'
  resources :genres, only: [:new, :create, :destroy]
  get 'tags/:tag', to: 'novels#index', as: :tag
  resources :relationships, only: [:create, :destroy]

end

app/models/novel.rb
class Novel < ApplicationRecord
  acts_as_paranoid
  # is_impressionable counter_cathe: true, unique: :all
  is_impressionable :counter_cache => true, :column_name => :impressions_count

  acts_as_taggable

  belongs_to :user
  belongs_to :genre, optional: true

  has_many :novel_content, dependent: :destroy

  validates :novel_title, presence: true, length: { maximum: 50 }
  validates :novel_about, presence: true, length: { maximum: 10000, minimum: 10 }
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :new, :destroy]
  before_action :correct_user, only: [:edit]
  before_action :user_admin, only: [:novels_admin_index]

  def index
    if params[:tag_name]
      puts 'tag_name'
      @novels = Novel.page(params[:page]).tagged_with(params[:tag_name]).order(created_at: 'desc')
      @novel_contents = NovelContent.where(novel_id: @novels)
      @likes = Like.where(novel_content_id: @novel_contents)
      @tags = Novel.all_tags.order('taggings_count desc')
      @novel_con = NovelContent.all.order(created_at: 'desc')
      @tag = @tags.find_by(name: params[:tag_name])
    elsif params[:genre_id]
      puts 'gnere_id'
      @novels = Novel.page(params[:page]).where(genre_id: params[:genre_id]).order(created_at: 'desc')
      @novel_contents = NovelContent.where(novel_id: @novels)
      @likes = Like.where(novel_content_id: @novel_contents)
      @tags = Novel.all_tags.order('taggings_count desc')
      @novel_con = NovelContent.all.order(created_at: 'desc')
      @genre = Genre.find_by(id: params[:genre_id])
    else
      puts 'other'
      @search = Novel.ransack(params[:q])
      @search_novels = @search.result.page(params[:page]).order(created_at: 'desc')
      @tags = Novel.all_tags.order('taggings_count desc')
      @novel_con = NovelContent.all.order(created_at: 'desc')
      # @paginatable_array = Kaminari.paginate_array(@search_novels).page(params[:page])
      # @novel_contents = NovelContent.where(novel_id: @search_novels)
      # @likes = Like.where(novel_content_id: @novel_contents)
      # @search_novels.each do |f|
      #   binding.pry
      #   @likes = Like.where(novel_content_id: f.novel_content)
      #   @comments = Comment.where(novel_content_id: f.novel_content)

      # end
    end
  end

  def show
    @novel = Novel.find(params[:id])
    @novel_contents = NovelContent.where(novel_id: params[:id])
    impressionist(@novel, nil, :unique => [:session_hash])
  end

  def edit
    @novel = Novel.find(params[:id])
  end

  def new
    @novel = Novel.new
  end

  def destroy
    @novel = Novel.find(params[:id])
    if @novel.destroy
      flash[:alert] = "#{@novel.novel_title}を削除しました"
      redirect_to novels_user_path(@novel.user)
    else
      render action: "edit"
    end
  end

  def novels_admin_index
    @novels = Novel.page(params[:page]).without_deleted
  end

  def ranking
    @like_ranks = NovelContent.find(Like.group(:novel_content_id).order('count(novel_content_id) desc').limit(5).pluck(:novel_content_id))
    @novel_most_viewed = Novel.order('impressions_count desc').limit(3)
    @novel_content_most_viewed = NovelContent.order('impressions_count desc').limit(5)
    @comment_ranks = NovelContent.find(Comment.group(:novel_content_id).order('count(novel_content_id) desc').limit(5).pluck(:novel_content_id))

    # binding.pry
    # @genre_most_viewed = @novel_genre.order('impressions_count desc').limit(3)
  end

  def create
    @novel = Novel.new(novel_params)
    @novel.user_id = current_user.id
    if @novel.save
      flash[:notice] = "一話目を投稿しよう！"
      redirect_to new_novel_novel_content_path(@novel.id)
    else
      render action: 'new'
    end
  end

  def update
    @novel = Novel.find(params[:id])
    if @novel.update(novel_params)
      flash[:notice] = "#{@novel.novel_title}を更新しました"
      redirect_to novel_path(@novel)
    else
      render action: "edit"
    end
  end

  def novel_restore
    @novel = Novel.only_deleted.find(params[:id]).restore
    flash[:notice] = "#{@novel.novel_title}を復元しました"
    redirect_to novels_admin_index_novels_path
  end

  private

  def novel_params
    params.require(:novel).permit(:novel_title, :novel_about, :tag_list, :genre_id)
  end

  def user_admin
    @novels = Novel.page(params[:page]).with_deleted
    if current_user.admin == false
      redirect_to root_path
    else
      render :novels_admin_index
    end
  end

  def correct_user
    @novel = Novel.find(params[:id])
    if current_user.admin || current_user.id == @novel.user_id
      render :edit
    else
      flash[:alert] = "権限がありません"
      redirect_to novel_path(@novel)
    end
  end
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/views/novels/_content.html.erb
<div class= "novel-box-show">
	<h3><%= link_to f.novel_content_title, novel_novel_content_path(f.novel_id , f.id) %></h3>
	作品名：<%= link_to f.novel.novel_title, novel_path(f.novel_id) %><br>
	投稿者：<%= link_to f.user.username , user_path(f.user.id)%><br>
	ホストユーザー：<%= link_to f.novel.user.username, user_path(f.novel.user.id) %><br>
	投稿日:<%= f.created_at.strftime('%Y/%m/%d/%H:%M') %>
	最終更新日:<%= f.updated_at.strftime('%Y/%m/%d/%H:%M') %>
	<br>
	<i class="far fa-comment-dots"></i><%= f.comments.count %>
	<i class="fas fa-heart" , style="color: red;"></i><%= f.likes.count %>
	<i class="fas fa-eye"></i><%= f.impressions_count %>
</div>

app/views/novels/_index_side.html.erb
<div class= "col-lg-3 col-md-3 col-xs-10 col-lg-offset-0 col-md-offset-0 col-xs-offset-1  col-lg-pull-6 col-md-pull-6">
	<div class= "new_content">
		<div class= "tag_cloud_head">
		  <h2>新着小説</h2>
	    </div>
        <% novel_con.first(5).each do |f| %>
        <div class= "novel-box-show">
			<h3><%= link_to f.novel_content_title, novel_novel_content_path(f.novel.id, f) %></h3>
				作品名：<%= link_to f.novel.novel_title ,novel_path(f.novel.id) %><br>
				投稿者：<%= link_to f.user.username , user_path(f.user.id)%><br>
				ホストユーザー：<%= link_to f.novel.user.username, user_path(f.novel.user.id) %><br>
				投稿日：<%= f.created_at.strftime('%Y/%m/%d/%H:%M') %>
				<br>
				<i class="far fa-comment-dots"></i><%= f.comments.count %>
				<i class="fas fa-heart" , style="color: red;"></i><%= f.likes.count %>
				<i class="fas fa-eye"></i><%= f.impressions_count %>
		</div>
        <% end %>
    </div>
</div>
<div class= "col-lg-3 col-md-3 col-xs-10 col-lg-offset-0 col-md-offset-0 col-xs-offset-1">
	<div class= "tag_cloud_head">
		<h2>タグクラウド</h2>
	</div>
	<div class= "tag_cloud">
        <% tags.each do |tag| %>
          <button class="tag">
          <%= link_to tag, novels_path(tag_name: tag.name) %>
          <i>(<%= tag.taggings_count %>)</i>
          </button>
        <% end %>
    </div>
</div>

app/views/novels/_novel.html.erb
<div class= "novel-box-show">
	<h3><%= link_to f.novel_title, novel_path(f.id) %></h3>
	<button class= "genre"><%= link_to f.genre.genre_name ,novels_path(genre_id: f.genre.id) %></button><br>
	<% f.tag_list.each do |tag|  %>
		<button class="tag">
			<%= link_to tag, novels_path(tag_name: tag) %>
		</button>
	<% end %>
	<div class ="open">
		<div class= "novel-about">
		<%= simple_format(f.novel_about) %>
		</div>
	</div>
	作成者：<%= link_to f.user.username, user_path(f.user.id) %><br>
	作成日：<%= f.created_at.strftime('%Y/%m/%d/%H:%M') %>
	<% if f.novel_content.exists? %>
	最終更新日：<%= f.novel_content.last.updated_at.strftime('%Y/%m/%d/%H:%M') %>
	<% else %>
	最終更新日：<%= f.updated_at.strftime('%Y/%m/%d/%H:%M') %>
	<%  end %>
	<div class= "open">
		参加ユーザー
		<i class= "fas fa-users"></i>
		:

		<%= f.novel_content.map(&:user).uniq.count %>
		人
		<% f.novel_content.map(&:user).uniq.each do |u| %>
	        <%= link_to u.username, user_path(u) %>
	    <% end  %>
	</div>
	<i class="far fa-eye"></i><%= f.impressions_count %><br>
	<i class="fas fa-heart" , style="color: red;"></i><%= all_likes_count(f) %>
	<i class="far fa-comment-dots"></i><%= all_comments_count(f) %>
	<i class="fas fa-eye"></i><%= all_views_count(f) %>
</div>

app/views/novels/_novel_content.html.erb
<div class= "novel-box-show">
	<h3><%= link_to f.novel_content.novel_content_title, novel_novel_content_path(f.novel_content.novel.id, f.novel_content.id) %></h3>
	作品名：<%= link_to f.novel_content.novel.novel_title ,novel_path(f.novel_content.novel.id) %><br>
	投稿者：<%= link_to f.novel_content.user.username , user_path(f.novel_content.user.id)%><br>
	ホストユーザー：<%= link_to f.novel_content.novel.user.username, user_path(f.novel_content.novel.user.id) %><br>
	投稿日：<%= f.novel_content.created_at.strftime('%Y/%m/%d/%H:%M') %>
	<br>
	最終更新日：<%= f.novel_content.updated_at.strftime('%Y/%m/%d/%H:%M') %>
	<br>
	<i class="far fa-comment-dots"></i><%= f.novel_content.comments.count %>
	<i class="fas fa-heart" , style="color: red;"></i><%= f.novel_content.likes.count %>
	<i class="fas fa-eye"></i><%= f.novel_content.impressions_count %>
</div>

app/views/novels/_ranking_novel.html.erb
<div class= "novel-box-show">
	<h4><%= "#{i}位 " %></h4>
	<h3><%= link_to f.novel_title, novel_path(f.id) %></h3>
	<button class= "genre"><%= link_to f.genre.genre_name ,novels_path(genre_id: f.genre.id) %></button><br>
	<% f.tag_list.each do |tag|  %>
		<button class="tag">
			<%= link_to tag, novels_path(tag_name: tag) %>
		</button>
	<% end %>
	<div class ="open">
		<div class= "novel-about">
		<%= simple_format(f.novel_about) %>
		</div>
	</div>
	作成者：<%= link_to f.user.username, user_path(f.user.id) %><br>
	作成日：<%= f.created_at.strftime('%Y/%m/%d/%H:%M') %>
	<% if f.novel_content.exists? %>
	最終更新日：<%= f.novel_content.last.updated_at.strftime('%Y/%m/%d/%H:%M') %>
	<% else %>
	最終更新日：<%= f.updated_at.strftime('%Y/%m/%d/%H:%M') %>
	<%  end %>
	<div class= "open">
		参加ユーザー
		<i class= "fas fa-users"></i>
		:

		<%= f.novel_content.map(&:user).uniq.count %>
		人
		<% f.novel_content.map(&:user).uniq.each do |u| %>
	        <%= link_to u.username, user_path(u) %>
	    <% end  %>
	</div>
	<i class="far fa-eye"></i><%= f.impressions_count %><br>
	<i class="fas fa-heart" , style="color: red;"></i><%= all_likes_count(f) %>
	<i class="far fa-comment-dots"></i><%= all_comments_count(f) %>
	<i class="fas fa-eye"></i><%= all_views_count(f) %>
</div>

app/views/novels/_ranking_novel_content.html.erb
<div class= "novel-box-show">
	<h4><%= "#{i}位 " %></h4>
	<h3><%= link_to f.novel_content_title, novel_novel_content_path(f.novel_id , f.id) %></h3>
	作品名：<%= link_to f.novel.novel_title, novel_path(f.novel_id) %><br>
	投稿者：<%= link_to f.user.username , user_path(f.user.id)%><br>
	ホストユーザー：<%= link_to f.novel.user.username, user_path(f.novel.user.id) %><br>
	投稿日:<%= f.created_at.strftime('%Y/%m/%d/%H:%M') %>
	最終更新日:<%= f.updated_at.strftime('%Y/%m/%d/%H:%M') %>
	<br>
	<i class="far fa-comment-dots"></i><%= f.comments.count %>
	<i class="fas fa-heart" , style="color: red;"></i><%= f.likes.count %>
	<i class="fas fa-eye"></i><%= f.impressions_count %>
</div>

app/views/novels/edit.html.erb
<%= render "common/header" %>
<div class= "body">
	<div class= "container" >
		<div class= "row">
			<div class ="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-xs-12">
			<% if @novel.errors.any? %>
			<div id="error_explanation">
				<ul>
					<h3><%= @novel.errors.count %>件のエラーです</h3>
					<% @novel.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
			<% end %>

			<%= form_with model: @novel, local: true do  |f| %>
			<div class= "field novel-field" >
				<%= f.label :novel_title, "作品名 ~50文字" %>
				<%= f.text_field :novel_title, placeholder: "作品名を入力　~50文字" %>
				<p id="counter-1">0文字</p>
			</div>
			<% if current_user.admin? %>
				<div class= "field">
					<%= f.label :novel_genre, "ジャンル" %><br>

					<%= f.collection_select :genre_id, Genre.all, :id, :genre_name, {prompt: @novel.genre.genre_name} %>
					<%=link_to "ジャンルを追加" , new_genre_path ,class: "btn btn-success btn-xs"%>
				</div>
			<% else %>
				<div class= "field">
					<%= f.label :novel_genre, "ジャンル" %><br>
					<%= f.collection_select :genre_id, Genre.all, :id, :genre_name, {prompt: @novel.genre.genre_name} %>
				</div>
			<% end %>
			<div class= "field novel-field">
				<%= f.label :novel_tag, "タグ(カンマ切り)" %>
				<%= text_field_tag "novel[tag_list]", @novel.tag_list.join(","), "date-role" => "tagsinput",  placeholder: "タグ1,タグ2,タグ3, ..."%>
			</div>
			<div class= "field">
				<%= f.label :novel_about, "あらすじ/説明  10~10000文字" %>
				<%= f.text_area :novel_about, placeholder: "あらすじ/説明  10~10000文字" %>
				<p id="counter-2">0文字</p>
			</div>
			<h4><%= f.submit "更新" ,class: "btn btn-primary btn-block" ,date:{ confirm: "更新しますか？"}%></h4>
			<% end %>
			<%= link_to "削除", novel_path(@novel), method: :delete , class: "btn btn-block btn-danger", data:{ confirm: "削除しますか？"} %>
			</div>
		</div>
	</div>
</div>
<%= render "common/footer" %>

app/views/novels/index.html.erb
<%= render "common/header" %>
<div class= "body">
	<%= render "common/alert" %>
	<div class= "container-fruid">
		<div class= "row">
			<div class= "col-lg-6 col-md-6  col-xs-10 col-lg-offset-0 col-md-offset-0 col-xs-offset-1 col-lg-push-3  col-md-push-3" >
				<%if @novels %>
					<% if params[:tag_name] %>
					  <%= "#{params[:tag_name]}の検索結果" %>:<%= "#{@tag.taggings_count}件" %>
					<% elsif params[:genre_id] %>
					  <%= "#{@genre.genre_name}の検索結果" %>:<%= "#{@genre.novel.count}件" %>
					<% end%>
					<% @novels.each do |novel| %>
						<%= render partial: "novel" ,locals: {f: novel} %>
					<% end %>
					<%= paginate @novels %>
				<% else %>

					<% @search_novels.each do |novel| %>
						<%= render partial: "novel" ,locals: {f: novel} %>
					<% end %>
					<%= paginate @search_novels %>
				<% end%>
			</div>
			<%= render partial: "index_side", locals: {novel_con: @novel_con, tags: @tags} %>
		</div>
	</div>
</div>
<%= render "common/footer" %>

app/views/novels/new.html.erb
<%= render "common/header" %>
<div class= "body">
	<div class= "container">
		<div class ="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-xs-12">
		<% if @novel.errors.any? %>
		<div id="error_explanation">
			<ul>
				<h3><%= @novel.errors.count %>件のエラーです</h3>
				<% @novel.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
		<h1>新規作成</h1>
		<%= form_with model: @novel, local: true do |f| %>
			<div class= "field novel-field" >
				<%= f.label :novel_title, "作品名 ~50文字" %>
				<%= f.text_field :novel_title, placeholder: "作品名を入力　~50文字" %>
				<p id="counter-1">0文字</p>
			</div>
			<% if current_user.admin? %>
				<div class= "field">
					<%= f.label :novel_genre, "ジャンル" %><br>
					<%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :genre_name), {prompt: "ジャンルを選択"} %>
					<%=link_to "ジャンルを追加" , new_genre_path ,class: "btn btn-success btn-xs"%>
				</div>
			<% else %>
				<div class= "field">
					<%= f.label :novel_genre, "ジャンル" %><br>
					<%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :genre_name), {prompt: "ジャンルを選択"} %>
				</div>
			<% end %>
			<div class= "field novel-field">
				<%= f.label :novel_tag, "タグ (カンマ切り)" %>
				<%= text_field_tag "novel[tag_list]", @novel.tag_list.join(","), "date-role" => "tagsinput",  placeholder: "タグ1,タグ2,タグ3, ..."%>
			</div>
			<div class= "field">
				<%= f.label :novel_about, "あらすじ/説明  10~10000文字" %>
				<%= f.text_area :novel_about, placeholder: "あらすじ/説明  10~10000文字" %>
				<p id="counter-2">0文字</p>
			</div>
			<h4><%= f.submit "一話目を書く" ,class: "btn btn-primary btn-block" ,date:{ confirm: "投稿しますか？"}%></h4>
		<% end %>
		</div>
	</div>
</div>
<%= render "common/footer" %>

app/views/novels/novels_admin_index.html.erb
<%= render "common/header" %>
<div class=body>
	<%= render "common/alert" %>
	<div  class="container">
		<div class= "row">
			<div  class= "col-lg-10 col-offset-1 col-md-10 col-md-offset-1 col-xs-12">
			    <div class= "table-responsive">
				<table class= "table table-hover">
					<thead>
						<tr>
							<th>ID</th>
							<th>タイトル</th>
							<th>投稿者</th>
							<th>話数</th>
							<th>編集</th>
							<th>削除</th>
						</tr>
					</thead>
					<tbody>
						<% @novels.each do |f| %>
						<tr>
							<td><%= f.id %></td>
								<% unless f.deleted_at? %>
									<td><%= link_to f.novel_title, novel_path(f) %></td>
									<% if f.user.deleted_at? %>
										<td><%= f.user.username %>退会済み</td>
										<td><%= f.novel_content.count %></td>
										<td><%= link_to "編集",  edit_novel_path(f), class: "btn btn-primary disabled" %></td>
									<% else  %>
										<td><%= link_to f.user.username, user_path(f.user.id) %></td>
										<td><%= f.novel_content.count %></td>
										<td><%= link_to "編集",  edit_novel_path(f), class: "btn btn-primary" %></td>
									<% end %>
										<td><%= button_to "削除", novel_path(f), method: :delete , class: "btn btn-danger", data:{ confirm: "削除しますか？"} %></td>
								<% else  %>
									<td><%= f.novel_title %></td>
									<% if f.user.deleted_at? %>
										<td><%= f.user.username %></td>
										<td><%= f.novel_content.count %></td>
										<td><%= link_to "編集",  edit_novel_path(f), class: "btn btn-primary disabled" %></td>
										<td><%= link_to "復元",novel_restore_novel_path(f), method: :get , class: "btn btn-success disabled"%></td>
									<% else  %>
										<td><%= link_to f.user.username, user_path(f.user.id) %></td>
										<td><%= f.novel_content.count %></td>
										<td><%= link_to "編集",  edit_novel_path(f), class: "btn btn-primary disabled" %></td>
										<td><%= link_to "復元",novel_restore_novel_path(f), method: :patch , class: "btn btn-success"%></td>
									<% end %>
								<% end %>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
				<%= paginate @novels %>
			</div>
		</div>
	</div>
</div>
<%= render "common/footer"  %>

app/views/novels/ranking.html.erb
<%= render "common/header" %>
<div class= "body">
	<div class= "container-fluid">
		<div class= "row">
			<div class= "col-lg-4 col-md-4 col-xs-10 col-lg-offset-0 col-md-offset-0 col-xs-offset-1">
				<div class= "ranking-box">
					<h4>Likeランキング<i class="fas fa-heart" , style="color: red;"></i></h4>
					<% @like_ranks.each.with_index(1) do |like, i| %>
					<%= render partial: "ranking_novel_content" ,locals: {f: like, i: i} %>
					<% end %>
				</div>
			</div>
			<div class= "col-lg-4 col-md-4 col-xs-10 col-lg-offset-0 col-md-offset-0 col-xs-offset-1">
				<div class= "ranking-box">
					<h4>PVランキング(小説)<i class="fas fa-eye"></i></h4>
					<% @novel_content_most_viewed.each.with_index(1) do |f,  i| %>
					<%= render partial: "ranking_novel_content" ,locals: {f: f, i: i} %>
					<% end %>
				</div>
			</div>
			<div class= "col-lg-4 col-md-4 col-xs-10 col-lg-offset-0 col-md-offset-0 col-xs-offset-1">
				<div class= "ranking-box">
					<h4>コメント数ランキング<i class="fas fa-users"></i></h4>
					<% @comment_ranks.each.with_index(1) do |like, i| %>
					<%= render partial: "ranking_novel_content" ,locals: {f: like, i: i} %>
					<% end %>
				</div>
			</div>
		</div>
		<div class= "row">
			<% @genres.each do |g| %>
			<div class= "col-lg-4 col-md-4 col-xs-10 col-lg-offset-0 col-md-offset-0 col-xs-offset-1">
				<div class= "ranking-box">
					<h4><%= g.genre_name %>PVランキング<i class="far fa-eye"></i></h4>

					<% if g.novel.count == 0 %>
					<p class= "non_content">まだ作品がありません</p>
					<% else %>
					<% genre_ranks(g)%>
					<% @genre_ranks.each.with_index(1) do |n, i| %>
					<%= render partial: "ranking_novel", locals: {f: n, i: i} %>
					<% end %>
					<% end %>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>
<%= render "common/footer" %>

app/views/novels/show.html.erb
<%= render "common/header" %>
<div class= "body">
  <%= render "common/alert" %>
  <div class ="novel_show_container">
    <div class ="index_container">
      <h2 id="novel-title"><%= @novel.novel_title %></h2>
      <h3><%= link_to @novel.user.username , user_path(@novel.user.id) %></h3>
      <button class= "genre">
        <%= link_to @novel.genre.genre_name ,novels_path(genre_id: @novel.genre.id) %>
      </button><br>
      <% @novel.tag_list.each do |tag|  %>
        <button class="tag">
          <%= link_to tag, novels_path(tag_name: tag) %>
        </button>
      <% end %><br>
      <div class= "join-user">
      参加ユーザー<br><% @novel.novel_content.map(&:user).uniq.each do |u| %>
                  <%= link_to u.username, user_path(u) %>
                  <% end  %>
      </div>
      <div class ="novel-about">
        <%= simple_format(@novel.novel_about) %>
      </div>
      <% if user_signed_in? %>
        <% if current_user.id == @novel.user_id || current_user.admin? %>
        <%= link_to "編集", edit_novel_path(@novel) , class: "btn btn-info"%>
        <% end %>
      <% end %>
    </div>
    <% if @novel_contents.exists? %>
    <table class ="table table-hover  table-responsive">
      <thead>
          <th id="novels_show">タイトル</th>
          <th id="novels_show">投稿者</th>
          <th id="novels_show">投稿日</th>
          <th id="novels_show">更新日</th>
          <th></th>
          <th></th>
          <th></th>
        </thead>
        <% @novel_contents.each do |f| %>
          <tbody>
            <tr>

              <td id= "title"><%= link_to f.novel_content_title, novel_novel_content_path(f.novel_id,f.id) %></td>
              <td ><%= link_to f.user.username, user_path(f.user.id) %></td>
              <td><%= f.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
              <td><%= f.updated_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
              <td><i class="far fa-comment-dots"></i><%= f.comments.count %></td>
              <td><i class="fas fa-heart" , style="color: red;"></i><%= f.likes.count %></td>
              <td><i class="fas fa-eye"></i><%= f.impressions_count %></td>
            </tr>
          </tbody>
        <% end %>
    </table>
    <% else %>
    <i>まだ投稿されていません</i><br>
    <% end %>
<span class= "logo"><%= link_to "TUDUKU!!",new_novel_novel_content_path(@novel.id), class: "btn btn-xl btn-success" %></span>
</div>
</div>
<%= render "common/footer" %>