config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :edit, :show, :update, :destroy], shallow: true do
  	member do
  		get 'like'
  		get 'history'
  		get 'follow'
      get 'novels'
      get 'novel_contents'
      patch 'user_restore'
  	end
  end
  resources :novels do
  	collection do
  		get 'ranking'
      get 'novels_admin_index'
    end
    member do
      patch 'novel_restore'
  	end
  	resources :novel_contents, only: [:show, :new, :edit, :update, :destroy, :create]  do
  		resources :comments, only: [:create, :destroy]
  		resource :likes, only: [:create, :destroy]
  		resource :history, only: [:create, :destroy]
        member do
          patch 'novel_content_restore'
  	     end
    end
  end
  root 'novels#index'
  get 'about/index'
  get 'novel_contents/index'
  resources :genres, only: [:new, :create, :destroy]
  get 'tags/:tag', to: 'novels#index', as: :tag
  resources :relationships, only: [:create, :destroy]

end

app/models/novel_content.rb
class NovelContent < ApplicationRecord
  acts_as_paranoid
  is_impressionable counter_cache: true

  belongs_to :novel
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :history, dependent: :destroy

  validates :novel_content_title, presence: true, length: { maximum: 50 }
  validates :novel_content_text, presence: true, length: { maximum: 50000, minimum: 300 }
  validates :novel_content_forewords, length: { maximum: 500 }
  validates :novel_content_afterwords, length: { maximum: 500 }

  def previous
    # @novel_content =  NovelContent.find(params[:id])
    # NovelContent.where("id < ?", self.id).order(id: "DESC").first
    # binding.pry
    # if NovelContent.where('id < @novel_content.id  and  novel_id = @novel_content.novel.id').exists?
    #   @prev = NovelContent.where('id < @novel_content.id  and  novel_id = @novel_content.novel.id').max
    # end
    # @prev = NovelContent.where('id < @novel_content  and  novel_id = @novel_content.novel')
  end

  def next
    # NovelContent.where("id > ?", self.id).order(id: "ASC").first
    @next = NovelContent.where('id > @novelcontent.id  and  novel_id = @novelcontent.novel.id')
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/controllers/novel_contents_controller.rb
class NovelContentsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :new, :destroy]
  before_action :correct_user, only: [:edit]
  before_action :user_admin, only: [:index]

  def index
  end

  def new
    @novel_content = NovelContent.new
    @novel = Novel.find_by(id: params[:novel_id])
  end

  def show
    @novel_content = NovelContent.find(params[:id])
    @novel = Novel.find_by(id: @novel_content.novel.id)
    if user_signed_in?
      new_history = @novel_content.history.new
      new_history.user_id = current_user.id
      if current_user.histories.exists?(novel_content_id: @novel_content)

        old_history = current_user.histories.find_by(novel_content_id: @novel_content)
        old_history.destroy
      end

      new_history.save

      histories_stock_limit = 20
      histories = current_user.histories.all
      if histories.count > histories_stock_limit
        histories[0].destroy
      end
    end

    if NovelContent.where("novel_id = ? and id < ?", @novel_content.novel.id, @novel_content.id).exists?
      @prev = NovelContent.where('id < ?  and  novel_id = ?', @novel_content.id, @novel_content.novel.id).max
    end
    if NovelContent.where("novel_id = ? and id > ?", @novel_content.novel.id, @novel_content.id).exists?
      @next = NovelContent.where('id > ?  and  novel_id = ?', @novel_content.id, @novel_content.novel.id).min
    end

    @comment = Comment.new
    @comments = @novel_content.comments
    impressionist(@novel_content, nil, :unique => [:session_hash])
  end

  def create
    @novel = Novel.find_by(id: params[:novel_id])
    @novel_content = NovelContent.new(novel_content_params)
    @novel_content.user_id = current_user.id
    @novel_content.novel_id = @novel.id
    if @novel_content.save
      flash[:notice] = "#{@novel.novel_title}に#{@novel_content.novel_content_title}を投稿しました"
      redirect_to novel_path(@novel.id)
    else
      render action: 'new'
    end
  end

  def edit
    @novel_content = NovelContent.find(params[:id])
  end

  def update
    @novel_content = NovelContent.find(params[:id])
    if @novel_content.update(novel_content_params)
      flash[:notice] = "更新しました"
      redirect_to novel_novel_content_path(@novel_content.novel.id, @novel_content.id)
    else
      render action: "edit"
    end
  end

  def destroy
    @novel_content = NovelContent.find(params[:id])
    @novel = Novel.find_by(id: @novel_content.novel_id)
    if @novel_content.destroy
      flash[:alert] = "#{@novel.novel_title}から#{@novel_content.novel_content_title}を削除しました"
      redirect_to novel_path(@novel)
    else
      render action: "edit"
    end
  end

  def novel_content_restore
    @novel_content = NovelContent.only_deleted.find(params[:id]).restore

    @novel = Novel.find_by(id: @novel_content.novel)
    flash[:notice] = "#{@novel.novel_title}に#{@novel_content.novel_content_title}を復元しました"
    redirect_to novel_contents_index_path
  end

  private

  def novel_content_params
    params.require(:novel_content).permit(:novel_content_title, :novel_content_text, :novel_content_forewords, :novel_content_afterwords)
  end

  def correct_user
    @novel_content = NovelContent.find(params[:id])
    if current_user.admin || current_user.id == @novel_content.user_id
      render action: "edit"
    else
      flash[:alert] = "権限がありません"
      redirect_to novel_novel_content_path(@novel_content.novel, @novel_content)
    end
  end

  def user_admin
    @novel_contents = NovelContent.page(params[:page]).with_deleted
    if current_user.admin == false
      redirect_to root_path
    else
      render :index
    end
  end
end

app/helpers/novel_contents_helper.rb
module NovelContentsHelper
end

app/views/novel_contents/edit.html.erb
<%= render "common/header" %>
<div class= "body">
	<div class= "container">
		<div class= "flash">
			<%= flash[:notice]  %>
		</div>
		<div class ="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-xs-12">
		<% if @novel_content.errors.any? %>
		<div id="error_explanation">
			<ul>
				<h3><%= @novel_content.errors.count %>件のエラーです</h3>
				<% @novel_content.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<h2 id= "novel-title"><%= @novel_content.novel.novel_title %></h2>
		ホストユーザー:<%= link_to @novel_content.user.username, user_path(@novel_content.novel.user) %>
		<h1>編集</h1>
		<%= form_with model: @novel_content, url: novel_novel_content_path, local: true do |f| %>
		<h3 style="color: red">*印は必須</h3>
			<div class= "field novel-field" >
				<%= f.label :novel_content_title, "タイトル　~500文字" %><i style="color: red">*</i>
				<%= f.text_field :novel_content_title, placeholder: "タイトルを入力　~50文字" %>
				<p id="counter-3">0文字</p>
			</div>
			<div class ="field content-field">
				<%= f.label :novel_content_forewords, "前書き  ~500文字" %>
				<%= f.text_area :novel_content_forewords, placeholder: "前書き ~500文字" %>
				<p id="counter-4">0文字</p>
			</div>
			<div>
				<%= f.label :novel_content_text, "本文　300~50000文字" %><i style="color: red">*</i>
				<%= f.text_area :novel_content_text, placeholder: "本文  300~50000文字" %>
				<p id="counter-5">0文字</p>
			</div>
			<div class ="field content-field">
				<%= f.label :novel_content_afterwords, "後書き　~500文字" %>
				<%= f.text_area :novel_content_afterwords, placeholder: "後書き ~500文字" %>
				<p id="counter-6">0文字</p>
			</div>
			<h4><%= f.submit "更新" ,class: "btn btn-primary btn-block", date:{ confirm: "更新しますか？"}%></h4>
		<% end %>
		<%= link_to "削除", novel_novel_content_path(@novel_content.novel_id, @novel_content), method: :delete , class: "btn btn-block btn-danger", data:{ confirm: "削除しますか？"} %>
</div>
</div>
</div>
<%= render "common/footer" %>

app/views/novel_contents/index.html.erb
<%= render "common/header" %>
<div class=body>
	<div  class="container">
		<div class= "row">
			<div  class= "col-lg-12  col-md-12 col-xs-12">
				<%= render "common/alert" %>
			    <div class= "table-responsive">
				<table class= "table table-hover">
					<thead>
						<tr>
							<th>ID</th>
							<th>タイトル</th>
							<th>投稿者</th>
							<th>作品名</th>
							<th>編集</th>
							<th>削除</th>
						</tr>
					</thead>
					<tbody>
						<% @novel_contents.each do |f| %>
						<tr>
							<td><%= f.id %></td>
							<% if f.novel == nil %>
								<% unless f.deleted_at? %>
									<td><%= f.novel_content_title %></td>
									<td><%= link_to f.user.username, user_path(f.user.id) %></td>
									<td>削除済み</td>
									<td><i class= "btn btn-primary disabled">編集</i></td>
									<td><i class= "btn btn-success disabled">復元</i></td>
								<% else %>
									<td><%= f.novel_content_title %></td>
									<% if f.user.deleted_at? %>
									<td><%= f.user.username %>退会済み</td>
									<% else %>
									<td><%= link_to f.user.username, user_path(f.user.id) %></td>
									<% end %>
									<td>削除済み</td>
									<td><i class= "btn btn-primary disabled">編集</i></td>
									<td><i class= "btn btn-success disabled">復元</i></td>
							    <% end %>
							<% else %>
								<% unless f.deleted_at? %>
									<td><%= link_to f.novel_content_title, novel_novel_content_path(f.novel, f) %></td>
									<td><%= link_to f.user.username, user_path(f.user.id) %></td>
									<td><%= link_to f.novel.novel_title, novel_path(f.novel) %></td>
									<td><%= link_to "編集",  edit_novel_novel_content_path(f.novel, f.id), class: "btn btn-primary disable" %></td>
									<td><%= button_to "削除", novel_novel_content_path(f.novel, f), method: :delete , class: "btn btn-danger", data:{ confirm: "削除しますか？"} %></td>
								<% else  %>
									<td><%= link_to f.novel.novel_title, novel_novel_content_path(f.novel, f) %></td>
									<td><%= link_to f.user.username, user_path(f.user) %></td>
									<td><%= link_to f.novel.novel_title, novel_path(f.novel) %></td>
									<td><%= link_to "編集",  edit_novel_novel_content_path(f.novel, f.id), class: "btn btn-primary disable" %></td>
									<td><%= link_to "復元",novel_content_restore_novel_novel_content_path(f.novel, f.id), method: :patch , class: "btn btn-success"%></td>
								<% end %>
							<% end %>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
				<%= paginate @novel_contents %>
			</div>
		</div>
	</div>
</div>
<%= render "common/footer"  %>

app/views/novel_contents/new.html.erb
<%= render "common/header"%>
<div class= "body">
	<%= render "common/alert" %>
	<div class= "container">
		<div class ="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-xs-12">
		<% if @novel_content.errors.any? %>
		<div id="error_explanation">
			<ul>
				<h3><%= @novel_content.errors.count %>件のエラーです</h3>
				<% @novel_content.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
		<h2 id= "novel-title"><%= @novel.novel_title %></h2>
		ホストユーザー:<%= link_to @novel.user.username, user_path(@novel.user) %>
		<h1><span class="logo">TUDUKI!!</span></h1>
		<%= form_with model: @novel_content ,url: novel_novel_contents_path, local: true  do |f| %>
		<h3 style="color: red">*印は必須</h3>
			<div class= "field novel-field" >
				<%= f.label :novel_content_title, "タイトル　~50文字" %><i style="color: red">*</i>
				<%= f.text_field :novel_content_title, placeholder: "タイトルを入力　~50文字" %>
				<p id="counter-3">0文字</p>
			</div>
			<div class ="field content-field">
				<%= f.label :novel_content_forewords, "前書き  ~500文字" %>
				<%= f.text_area :novel_content_forewords, placeholder: "前書き ~500文字" %>
				<p id="counter-4">0文字</p>
			</div>
			<div>
				<%= f.label :novel_content_text, "本文　300~50000文字" %><i style="color: red">*</i>
				<%= f.text_area :novel_content_text, placeholder: "本文  300~50000文字" %>
				<p id="counter-5">0文字</p>
			</div>
			<div class ="field content-field">
				<%= f.label :novel_content_afterwords, "後書き　~500文字" %>
				<%= f.text_area :novel_content_afterwords, placeholder: "後書き ~500文字" %>
				<p id="counter-6">0文字</p>
			</div>
			<h4><span  class= "logo"><%= f.submit "TUDUKU!!" ,class: "btn btn-primary btn-block" ,method: :post, date:{ confirm: "投稿しますか？"}%></span></h4>
		<% end %>
</div>
</div>
</div>
<%= render "common/footer" %>

app/views/novel_contents/show.html.erb
<%= render "common/header" %>
<div class= "body">
	<%= render "common/alert" %>
	<div class= "novel_content_head">
		<%= link_to @novel.novel_title, novel_path(@novel) %>
		/
		<%= link_to @novel.user.username, user_path(@novel.user.id) %>
	</div>
	<div class= "novel-content-title">
		<h2><%= @novel_content.novel_content_title %></h2>
		<h4><%= link_to @novel_content.user.username, user_path(@novel_content.user.id) %></h4>
		<% if user_signed_in? %>
		    <% if current_user.id == @novel_content.user_id || current_user.admin? %>
	        <%= link_to "編集", edit_novel_novel_content_path(@novel_content.novel.id, @novel_content.id) , class: "btn btn-info"%>
       		<% end %>
       	<% end %>
    </div>
	<div class= "novel-content-foreword">
		<%= simple_format(@novel_content.novel_content_forewords) %>
	</div>
	<div class ="novel-content-text">
		<%= simple_format(@novel_content.novel_content_text) %>
	</div>
	<div class= "novel-content-afterword">
		<%= simple_format(@novel_content.novel_content_afterwords) %>
	</div>
	<div class= "novel-content-botton">

		<% if @prev.present? %>
		<%= link_to "前へ",novel_novel_content_path(@novel, @prev) %>
		<% else %>
		×
		<% end %>
		</span>
		|
		<span class= "botton-btn">
		<%= link_to "目次", novel_path(@novel) %>
		</span>
		|
		<span class= "botton-btn">
		<% if @next.present? %>
		<%= link_to "次へ", novel_novel_content_path(@novel, @next)  %>
		<% else %>
		<span  class= "logo">
		<%= link_to "TUDUKU!!",new_novel_novel_content_path(@novel.id), class: "btn btn-xl btn-success" %>
	    </span>
		<% end %>
		<div id= 'likes_buttons_<%= @novel_content.id %>'>
			<%= render partial: 'likes/like', locals: {novel:  @novel, novel_content:  @novel_content} %>
		</div>
	 	</span>
	</div>
	<div class= "comment">
		<h4>コメント</h4>
		<div id= "comments_area" >
			
			<%= render partial: "comments/index",  locals: {comments: @comments, novel_content: @novel_content} %>
			
		</div>
		<% if user_signed_in? %>
		<%= render partial: "comments/form", locals: {comment: @comment, novel_content: @novel_content, novel: @novel} %>
		<% end %>
	</div>
</div>
<%= render "common/footer" %>